# _ChRIS_ 2023 -- User IDs and file permission model

## Abstract

_ChRIS2016_ has no real concept of user ids and there is no file permission model. A hard coded user called "chris" is assumed to be a "superuser" and has undefined and undiscoverable permissions and access. Similarly, "ordinary" users have less permissions, but the exact enumeration and meaning of what permissions exist is not defined.

## Introduction

The lack of any concept of explicit permissions on files and object in CUBE in _ChRIS2016_ has reached its end-of-life. In order for ChRIS to develop further, a pervasive and robust permission model needs to be defined and clear to users of the system.

Similarly, _ChRIS2016_ has a hard coded super user called `chris`. The permissions such as they currently exist in _ChRIS2016_ simply provide elevated access to this user.

## What currently exists

Pretty much very little. Files, plugins, directories -- any and all objects in ChRIS have no embedded permissions. Moreover, there is no concept of user ids, which means that a special named user (by convention called `chris`) has special powers simply by virtue of having this special name.

## Proposal

### User IDs

We propose to simply adopt a simplified POSIX user id scheme:

* all users have numerical ids in addition to their string names
* a "root" user exists that has a user id of 0.
* ownership is specified by user id, which is mapped back to a string name

### No groups

We propose to not have a concept of groups. This simplifies some sharing considerations, but has downstream implications that need to be carefully enumerated (see later).

### Permission model

Similarly the proposal is for a simplified and generalized model of the standard POSIX permission concept or `rwx` (read/write/execute) for every "listable" object in ChRIS filesystem space. The semantics of each of the read/write/execute need to be carefully specified.

### Object permission example

The proposed simplification from POSIX is simply that the three tuple concept of `owner,group,other` is reduced to `owner`, but retains the `[df]rwx` bits:

[options="header"]
|==============================================
| type | name      | owner
| dir  | Pictures  | rudolph:rwx,jack:r,jill:rwx
| file | image.dcm | rudolph:rwx,ellen:r,jack:rwx
| file | filter    | rudolph:rwx
|==============================================

Importantly and a generalization of the POSIX model, the above model simply breaks the standard 3 tuple and explicitly associates ownership permissions directly with a user, resulting in the idea of multiple, specific _owners_.

By convention, the first "owner" is considered the primary owner.

Moreover, since the POSIX model tuple users `group,other` to define sharing, we propose to explicitly set sharing permissions as `<username>:<bitpermission>`. So, in the above the file `image.dcm` is shared read-only with the `ellen` user, and read-write-execute with the `jack` user. Thus, if `ellen` were to

[source,console]
----
(ellen) $ cd /home/rudolph
(ellen) /home/rudolph$ ls
image.dcm
----

But the `jack` user would see:

[source,console]
----
(jack) $ cd /home/rudolph
(jack) /home/rudolph$ ls
Pictures
image.dcm
----

and `jill` would see

[source,console]
----
(jill) $ cd /home/rudolph
(jill) /home/rudolph$ ls
Pictures
----

## Implications

Group user aliases could be defined (which according to RFC 13-ChRISFS.adoc could live under `/etc`) to allow for group-based sharing. An important alias is `all` which denotes "all" users, thus if `rudolph` has a feed, it would could be made "public" with:

|============================================
| type | name      | owner
| dir  | feed_123  | rudolph:rwx, all:r
|============================================

In this model, for public browsing, a public user is the `all` user and could only "see" objects that have an `all` owner with at least a `read` bit set.

## Permission meanings

TBD.


















