= YAML File-Representations of _ChRIS_ Pipelines
Jennings <Jennings.Zhang@childrens.harvard.edu>
:status: accepted

Status: {status}

== Abstract

This document describes the motivation for the
xref:../specs/YAML_Pipelines.adoc[_ChRIS_ YAML Pipelines Schema].

== Background

Currently there is no standardized file representation of a _ChRIS_ pipeline.

For the most part, pipelines are represented as files containing the
JSON data a user would POST to `/api/v1/pipelines/` to create a pipeline.

The first approach was to use a shell script in which the JSON data is hard-coded.

https://github.com/FNNDSC/CHRIS_docs/blob/050ccd119d4e0e4c3f0a321c9ab9a743325b04b0/pipelines/fetal_brain_reconstruction.sh

A second approach was to use a script which uploads JSON files
as pipelilnes with the `application/json` media type, where in the
source file, the `plugin_tree` is a JSON object instead of a
serialized string representing a JSON object.
(CUBE requires `plugin_tree` to be a string instead of an object,
due to the limitations of http://amundsen.com/media-types/collection/format/[Collection+JSON]).
This script would serialize `plugin_tree` as a string.

Pipeine upload script: https://github.com/FNNDSC/CHRIS_docs/blob/4222eada1911daa0e4a25e74db9fcf140e0a49d0/pipelines/pipeline_upload.sh

JSON pipeline files examples: https://github.com/FNNDSC/CHRIS_docs/tree/4222eada1911daa0e4a25e74db9fcf140e0a49d0/pipelines/source

== Motivation

The protocol for creating a pipeline in _ChRIS_, including the `application/json`
and `application/vnd.collection+json` schemas, are not user-friendly.

This document defines a YAML schema which describes _ChRIS_ pipelines,
and how to interpret the schema as JSON data which satisfies the
protocol for creating a pipeline in _ChRIS_ via a POST request to `/api/v1/pipelines/`.

== Schema

Refer to xref:../specs/YAML_Pipelines.adoc[_ChRIS_ YAML Pipelines Schema]

== Integration

Client tools can be developed to parse this schema as an easier way to
create _ChRIS_ pipelines from a file representation.

=== Status

https://github.com/FNNDSC/chrs/releases/tag/chrs%2F0.0.4[`chrs` version 0.0.4]
added functionality for uploading "YAML Pipelines" to _ChRIS_ (`chrs pipeline-file add`) and converting between the previously described JSON file-represetnations
to the new "YAML Pipelines" schema (`chrs pipeline-file convert`).
