= Tunnel Strategy for Private Remote Computes
Jennings Zhang <Jennings.Zhang@childrens.harvard.edu>

== Abstract

_OpenSSH_ server and `autossh` are used within `docker-compose` managed
applications to expose services on a private network to other services
outside the LAN.

== Introduction

You want to make services within a private network accessible to local containers
managed by `docker-compose`. E.g. _CUBE_ (i.e. backend) running in a DMZ while
_pfcon_ (i.e. satelite service) is inside a private LAN.

== Satelites

Run `ssh-keygen` (do not specify a password) and rename the private key to `secrets/ssh/id_rsa` 

.docker-compose.yml
[source,yaml]
----

version: '3.7'

services:
  autossh:
    image: jnovack/autossh
    environment:
      SSH_REMOTE_USER: premote-user
      SSH_REMOTE_HOST: cube.example.com
      SSH_MODE: -R
      SSH_REMOTE_PORT: 26552
      SSH_TUNNEL_PORT: 2005
      SSH_TARGET_HOST: pfcon
      SSH_TARGET_PORT: 5005
      SSH_BIND_IP: "*"
      SSH_KEY_FILE: /run/secrets/ssh-privatekey
    secrets:
      - ssh-privatekey
    restart: unless-stopped

  pfcon:
    image: fnndsc/pfcon:3.0.0.0
    environment:
      COMPUTE_SERVICE_URL: http://pman:5010/api/v1/
      DATA_SERVICE_URL: http://pfioh:5055/api/v1/cmd
    env_file:
      - secrets/pfcon.env
    depends_on:
      - pman
      - pfioh
    restart: on-failure

  pfioh:
    image: fnndsc/pfioh:3.0.2
    command: ["--forever", "--httpResponse", "--createDirsAsNeeded", "--storeBase", "/hostFS/storeBase", "--port", "5055"]
    volumes:
      - pfioh-remote:/hostFS/storeBase
    restart: on-failure

  pman:
    image: fnndsc/pman:3.1.0
    environment:
      CONTAINER_ENV: swarm
      PMAN_DOCKER_VOLUME: chris-pfioh-remote-data
    env_file:
      - secrets/pman.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pfioh-remote:/hostFS/storeBase
    restart: on-failure

volumes:
  pfioh-remote:
    name: chris-pfioh-remote-data
secrets:
  ssh-privatekey:
    file: secrets/ssh/id_rsa
----

== Backend

In the local backend network, run a SSH server.

.docker-compose.yml
[source,yaml]
----
version: '3.7'
services:
  tunnels:
    image: ghcr.io/linuxserver/openssh-server
    ports:
      - "26552:2222"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      USER_NAME: premote-user
      DOCKER_MODS: "linuxserver/mods:openssh-server-ssh-tunnel"  # GatewayPorts clientspecified
    volumes:
      - ./tunnel:/config
    restart: unless-stopped
    networks:
      local:
        aliases:
          - tunnels.local
  chris:
    image: prod/chris:2.0.0
    networks:
      - local

networks:
  local:
----

After the server starts up, add public SSH keys to `./tunnel/.ssh/authorized_keys`

Add the compute environment:

[source,bash]
----
docker-compose exec chris plugins/services/manager.py add remote-name http://tunnels.local:2005/api/v1/
----

== Diagram

----

 +------+      +-----+
 | CUBE | ---- | SSH |
 +------+      +-----+
                 |              DMZ
===================================
                 |         internal
            +---------+
            | autossh |
            +---------+
                 |
+------+      +-------+      +-------+
| pman | ---- | pfcon | ---- | pfioh |
+------+      +-------+      +-------+
----

== Details

Working on `fnndsc/chris` build 2021-02-22, pfcon v3.0.0.0

== TODO

Faster? https://wiki.archlinux.org/index.php/OpenSSH#Speeding_up_SSH
