= Getting Started -- Simple Steps
Jennings Zhang <Jennings.Zhang@childrens.harvard.edu>

:sectnums:

== Prerequisites

All you need installed is Python, version 3.8 or later.

To share your app publicly you'll need an account on

- https://github.com (for your app's code)
- https://hub.docker.com/ (for your app's executable)
- https://chrisstore.co/ (for your app's details)

== Set up

First, install the `cookiecutter` tool:

[source,shell]
----
pip install -U cookiecutter
----

Then generate the starter code:

[source,shell]
----
cookiecutter https://github.com/FNNDSC/cookiecutter-chrisapp.git
----

For `app_type` choose "ds" (_data synthesis_ -- learn about the difference in our https://chrisstore.co/docs/fsdsTHISPAGEDNE[documentation])

== Creating a repository

Create a new _public_ repository on https://github.com.

CAUTION: don't initialize the repo with a `README`, a _license_, or a `.gitignore` file.

== Upload your code

Follow Github's instructions to add your files to _git_. For example, given a repo name `pl-projectapp` It should look like

[source,shell]
----
cd pl-projectapp
git add -A
git commit -m "First commit"
git remote add origin https://github.com/FNNDSC/pl-projectapp.git
git push origin master
----

== Build container images

Set up automatic builds on Dockerhub by following the instructions here:

https://docs.docker.com/docker-hub/builds/#configure-automated-build-settings

TIP: Keep the default build rule (source: `master`, tag: `latest`), then click `Trigger&nbsp;▶`

== Register your plugin

Produce a _representation_ (in JSON) of your app's metadata.
In the example below, replace "projectapp" with the name of your app.

[source,shell]
----
pip install -e .
projectapp --savejson $PWD
----

A new file should have appeared with a filename suffix `.json`, e.g. `Projectapp.json`.
It's ready to be uploaded to
https://chrisstore.co/create

:sectnums!:
== Next Steps

Congratulations! Your app is now on chrisstore.co.

To read on about advanced tips and tricks, visit https://chrisstore.co/docs
