= MOC Integration

== Abstract
This document describes the steps that are required to get ChRIS up and running on the MOC. The intended audience is ChRIS developers.

. xref:#registering-to-mass-open-cloud[Registering to Mass Open Cloud]
. xref:#adding-projects-to-openshift-and-openstack[Adding Projects to Openshift and Openstack]
. xref:#installing-openshift-cli-tool[Installing Openshift CLI Tool]
. xref:#creating-secrets-on-openshift-using-cli-tool[Creating Secrets on Openshift Using CLI Tool]
. xref:#deploying-pfioh-on-openshift[Deploying Pfioh on Openshift]
. xref:#deploying-pman-on-openshift[Deploying Pman on Openshift]
. xref:#running-test-scripts-on-openshift[Running Test Scripts on Openshift]


== Registering to Mass Open Cloud
In order to get an account from MOC, you should submit an account request. Follow this link -> https://massopen.cloud/request-an-account/[Request Account on MOC]

If you want to learn more about adding users to your Openstack project, follow this link -> https://support.massopen.cloud/kb/faq.php?id=22[Add Users to Openstack Project]

If your access is approved, Follow these links to login to the Openshift and Openstack platforms -> https://k-openshift.osh.massopen.cloud:8443/[Openshift] | http://kaizen.massopen.cloud/[Openstack]

You should be able to login to these platforms by using your `SSO` credentials.


== Adding Projects to Openshift and Openstack

== Installing Openshift CLI Tool

== Creating Secrets on Openshift Using CLI Tool

== Deploying Pfioh on Openshift

== Deploying Pman on Openshift

== Running Test Scripts on Openshift