= _ChRIS_ YAML Pipeline Schema
Jennings <Jennings.Zhang@childrens.harvard.edu>
:status: experimental

Status: {status}

See xref:../rfcs/2-pipeline_yaml.adoc[RFC #2].

== Definitions

This document defines a YAML schema for defining _ChRIS_ pipelines.
A generalized description of this schema could be
"title-indexed, file-based represetnation of a _ChRIS_ pipeline."
For short, this schema shall be known as a "YAML pipeline."

== Schema

=== `name`

Type: string

Name of pipeline.

=== `authors`

Type: string

Names and emails of the authors of this pipeline.

`authors` **may** be in the format: `Name1 <email1>; Name2 <email2>; ...`

=== `category`

Type: string

Name of category which this pipeline is related to.

=== `description`

Type: string

Description of pipeline.

=== `locked`

Type: boolean

Default: false

`true` indicates that the pipeline may be edited by its owner.

[#plugin_tree]
=== `plugin_tree`

Type: list[Piping]

Pipeline DAG definition. Each element of `plugin_tree` is called a "Piping"
and can be thought of as a template for plugin instances to create.

[#piping-title]
=== `plugin_tree[*].title`

Type: string

Description of piping. `title` must be unique for all elements of <<plugin_tree>>.

NOTE: `title` is not (currently) included in the _ChRIS_ pipeline creation protocol.

[#piping-plugin]
=== `plugin_tree[*].plugin`

Type: string

Plugin which to create a plugin instance of.

`plugin` is a string and it matches the pattern `.*\s+v\d+(\.\d+)*`,
where the substring after the right-most "v" in `plugin` is interpreted
as `plugin_version`, and the right-whitespace trimmed substring before
the right-most "v" in `plugin` is interpreted as `plugin_name`.

=== `plugin_tree[*].plugin_parameter_defaults`

Type: Optional[map[string, any]]

Default parameter values.

=== `plugin_tree[*].previous`

Type: string | `null`

A <<piping-title>> corresponding to some other element which exists in <<plugin_tree>>.

`previous` is serialized as `{"previous_index": N}` where `N` is the
index of the element indicated by `previous`.

== Examples

=== Automatic Fetal Brain Reconstruction Pipeline

==== YAML

```yaml
name: "Automatic Fetal Brain Reconstruction Pipeline v1.0.0"
authors: "Jennings Zhang <Jennings.Zhang@childrens.harvard.edu>"
category: "MRI"
description: "Automatic fetal brain reconstruction pipeline developed by Kiho's group at the FNNDSC. Features machine-learning based brain masking and quality assessment."
locked: false
plugin_tree:
- title: "Brain Masking"
  plugin: pl-fetal-brain-mask v1.2.1
  previous: null
- title: "N4 Bias Field Correction"
  plugin: pl-ANTs_N4BiasFieldCorrection v0.2.7.1
  previous: "Brain Masking"
  plugin_parameter_defaults:
    inputPathFilter: "extracted/0.0/*.nii"
- title: "Automatic Fetal Brain Assessment"
  plugin: pl-fetal-brain-assessment v1.3.0
  previous: "N4 Bias Field Correction"
- title: "IRTK Reconstruction"
  plugin: pl-irtk-reconstruction v1.0.3
  previous: "Automatic Fetal Brain Assessment"
```

==== vnd.collection+JSON Representation

```json
{
  "template": {
    "data": [
      {
        "name": "name",
        "value": "Automatic Fetal Brain Reconstruction Pipeline v1.0.0"
      },
      {
        "name": "authors",
        "value": "Jennings Zhang <Jennings.Zhang@childrens.harvard.edu>"
      },
      {
        "name": "Category",
        "value": "MRI"
      },
      {
        "name": "description",
        "value": "Automatic fetal brain reconstruction pipeline developed by Kiho's group at the FNNDSC. Features machine-learning based brain masking and quality assessment."
      },
      {
        "name": "locked",
        "value": false
      },
      {
        "name": "plugin_tree",
        "value": "[{\"plugin_name\":\"pl-fetal-brain-mask\",\"plugin_version\":\"1.2.1\",\"previous_index\":null},{\"plugin_name\":\"pl-ANTs_N4BiasFieldCorrection\" ,\"plugin_version\":\"0.2.7.1\",\"previous_index\":0,\"plugin_parameter_defaults\":[{\"name\":\"inputPathFilter\",\"default\":\"extracted/0.0/*.nii\"}]},{\"plugin_name\":\"pl-fetal-brain-assessment\",\"plugin_version\":\"1.3.0\",\"previous_index\":1},{\"plugin_name\":\"pl-irtk-reconstruction\",\"plugin_version\":\"1.0.3\",\"previous_index\":2}]"
      }
    ]
  }
}
```
